[package]
name = "price-source-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]

service-sdk = { git = "https://github.com/MyJetTools/service-sdk", tag = "0.2.6" }
tokio = "*"
async-trait = "*"
